SELECT  ISSUE_MON 
       ,PURC_MON_NEW 
       ,COUNT(PRODUCT_DIVIDE) AS counts
FROM `he_tv_svc_global_output_summary`
WHERE `PRODUCT_DIVIDE` IN ('LED_FHD', 'LED_UHD', 'OLED' ) 
AND ISSUE_MON >= 201810 
AND ISSUE_MON <= 202109 
AND PURC_MON_NEW >= 201810 
AND PURC_MON_NEW <= 202109 
AND DATA_DT <= 20210326 
GROUP BY  ISSUE_MON 
         ,PURC_MON_NEW;


SELECT  ISSUE_MON 
       ,PURC_MON_NEW 
       ,COUNT(PRODUCT_DIVIDE) AS counts;
FROM `he_tv_svc_global_output_summary`
WHERE `PRODUCT_DIVIDE` IN ('LED_FHD', 'LED_UHD', 'OLED' ) 
AND ISSUE_MON >= 201810 
AND ISSUE_MON <= 202109 
AND PURC_MON_NEW >= 201810 
AND PURC_MON_NEW <= 202109 
AND DATA_DT <= 20210326 
GROUP BY  ISSUE_MON 
         ,PURC_MON_NEW;


SELECT  PURC_MON 
       ,QTY 
       ,SALES_CORP
FROM `he_tv_sellin_sales_output_summary`
WHERE `PRODUCT_DIVIDE` IN ('LED_FHD', 'LED_UHD', 'OLED' ) 
AND PURC_MON >= 201810 
AND PURC_MON <= 202109 
AND DATA_DT <= 20210326;

SELECT  PURC_MON 
       ,QTY 
       ,PROD_CORP
FROM `he_tv_sellin_prod_output_summary`
WHERE `PRODUCT_DIVIDE` IN ('LED_FHD', 'LED_UHD', 'OLED' ) 
AND PURC_MON >= 201810 
AND PURC_MON <= 202109 
AND DATA_DT <= 20210326;  